# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Elements Registration

on:
  schedule:
    - cron:  '0 11 * * *'
    # This runs at 10:00 AM UTC each day.
    # * is a special character in YAML so you have to quote this string
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'test'
      tags:
        description: 'Test scenario tags'  
permissions:
  contents: read

  


jobs:
  build:

    runs-on: ubuntu-latest
    env:
        ELEMENTS_EMAIL: ${{ secrets.ELEMENTS_EMAIL }}
        ELEMENTS_PASSWORD: ${{ secrets.ELEMENTS_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: execute script 
      run: python elements.py
